# Generated by Django 4.2.1 on 2023-05-12 19:34

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usernames', models.CharField(max_length=255)),
                ('nombre_1', models.CharField(max_length=50)),
                ('nombre_2', models.CharField(max_length=50)),
                ('apellido_1', models.CharField(max_length=50)),
                ('apellido_2', models.CharField(max_length=50)),
                ('tipo_documentacion', models.CharField(max_length=3)),
                ('cedula', models.CharField(max_length=8, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='emails')),
                ('area', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
