# Generated by Django 4.2.1 on 2023-05-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser',
            table=None,
        ),
    ]
