# Generated by Django 4.2.1 on 2023-05-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_authuser_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='usernames',
            new_name='username',
        ),
    ]
