# Generated by Django 4.2.1 on 2023-06-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_authuser_apellido_1_alter_authuser_apellido_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(unique=True, verbose_name='Nombre del area'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='apellido_1',
            field=models.CharField(max_length=50, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='apellido_2',
            field=models.CharField(max_length=50, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.area'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='cedula',
            field=models.CharField(max_length=8, unique=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='nombre_1',
            field=models.CharField(max_length=50, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='nombre_2',
            field=models.CharField(max_length=50, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.rol'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='tipo_documentacion',
            field=models.CharField(choices=[('V', 'Venezolano')], default='V', max_length=4),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(unique=True, verbose_name='Nombre del rol administrativo'),
        ),
    ]
