# Generated by Django 4.2.1 on 2023-06-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_authuser_username_alter_area_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='tipo_documentacion',
            field=models.CharField(choices=[('V', 'Venezolano')], default='V', max_length=1),
        ),
    ]
