# Generated by Django 4.2.1 on 2023-06-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_periodos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Periodos',
        ),
    ]
