# Generated by Django 4.2.1 on 2023-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_authuser_apellido_1_alter_authuser_apellido_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='apellido_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='apellido_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='cedula',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='emails'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='nombre_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='nombre_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='rol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='tipo_documentacion',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
