# Generated by Django 4.2.1 on 2023-06-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_tutores_nombre_tutores_apellido_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutores',
            name='tipo_documentacion',
            field=models.CharField(choices=[('V', 'Venezolano')], default='V', max_length=1),
        ),
    ]
