# Generated by Django 4.2.1 on 2023-05-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_authuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='last_name',
        ),
    ]
