# Generated by Django 4.2.1 on 2023-06-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_authuser_tipo_documentacion'),
        ('authentication', '0008_alter_tutores_tipo_documentacion'),
    ]

    operations = [
    ]
