# Generated by Django 4.2.1 on 2023-06-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_merge_20230623_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='tipo_documentacion',
            field=models.CharField(choices=[('V', 'Venezolano')], default='V', max_length=4),
        ),
    ]
