# Generated by Django 4.2.1 on 2023-05-12 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_area_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.area'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.rol'),
        ),
    ]
