# Generated by Django 4.2.1 on 2023-05-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_authuser_area_alter_authuser_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='area',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='rol',
        ),
        migrations.AddField(
            model_name='area',
            name='nombre',
            field=models.CharField(null=True, unique=True, verbose_name='Nombre del area'),
        ),
        migrations.AddField(
            model_name='rol',
            name='nombre',
            field=models.CharField(null=True, unique=True, verbose_name='Nombre del rol administrativo'),
        ),
    ]
