# Generated by Django 4.2.1 on 2023-05-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_area_area_remove_rol_rol_area_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='create_date',
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='Nombre del area'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='cedula',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='tipo_documentacion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='Nombre del rol administrativo'),
        ),
    ]
