# Generated by Django 4.2.1 on 2023-05-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_SC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('tematica', models.CharField(max_length=200)),
                ('tutor', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('coordinador', models.CharField(max_length=200)),
            ],
        ),
    ]
