# Generated by Django 4.2.1 on 2023-05-30 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('biblioteca_SC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_sc',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.area'),
        ),
    ]
