# Generated by Django 4.2.1 on 2023-06-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_SC', '0002_alter_project_sc_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_sc',
            options={'verbose_name': 'Proyecto de servicio comunitario', 'verbose_name_plural': 'Proyectos de servicio comunitario'},
        ),
    ]
