# Generated by Django 4.2.1 on 2023-05-19 16:40

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_SC', '0003_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_sc',
            name='file',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='./projects'),
        ),
        migrations.AlterField(
            model_name='map',
            name='map_data',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='./maps'),
        ),
        migrations.AlterField(
            model_name='project_sc',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
