# Generated by Django 4.2.1 on 2023-05-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_SC', '0004_project_sc_file_alter_map_map_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
    ]
