# Generated by Django 4.2.1 on 2023-06-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_SC', '0006_alter_project_sc_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_sc',
            name='tutor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
