# Generated by Django 4.2.1 on 2023-06-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_SC', '0004_alter_project_sc_autor_alter_project_sc_file_and_more'),
        ('biblioteca_SC', '0010_remove_project_sc_tutor_project_sc_tutor'),
    ]

    operations = [
    ]
