# Generated by Django 4.2.1 on 2023-06-23 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_tutores_options_programa'),
        ('biblioteca_SC', '0012_alter_project_sc_periodo_alter_project_sc_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_sc',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.programa'),
        ),
    ]
